### ISSUE TITLE
getJSON error

### ISSUE THREAD

**Issue by damoncasale** [Rock48/node-steamlytics#2]
Steamlytics went down today and is emitting "broken" JSON, like so:

{"success":false,"message":"A server error has occurred. Please try again later."}{"success":false,"message":"A server error has occurred. Please try again later."}

This string obviously doesn't parse as valid JSON.  It throws an error which isn't properly caught, breaking the constructor call.

**Comment by Rock48** [comment]
This was actually fixed in e20099a4e4cfba93e752f01efd2a1d9f66d15c08 - I just never published it to npm.

**Comment by Rock48** [comment]
Fixed in 1.4.3
